// Copyright ©️ 2026 Ian Renton <ian@ianrenton.com>
// SPDX-License-Identifier: MPL-2.0
//
// Data was taken from the RSGB Contest Committee website page at https://www.rsgbcc.org/vhf/rules/2025/postcode.shtml
// This supports an unofficial two-letter form for the single-letter postcode regions such as B for Birmingham is given
// as BM. In this list I have included both forms.

export const RSGB_POSTCODE_DISTRICTS = {
  AB: 'Aberdeen',
  AL: 'St Albans',
  B: 'Birmingham',
  BM: 'Birmingham',
  BA: 'Bath',
  BB: 'Blackburn',
  BD: 'Bradford',
  BH: 'Bournemouth',
  BL: 'Bolton',
  BN: 'Brighton',
  BR: 'Bromley',
  BS: 'Bristol',
  BT: 'Belfast',
  CA: 'Carlisle',
  CB: 'Cambridge',
  CF: 'Cardiff',
  CH: 'Chester',
  CM: 'Chelmsford',
  CO: 'Colchester',
  CR: 'Croydon',
  CT: 'Canterbury',
  CV: 'Coventry',
  CW: 'Crewe',
  DA: 'Dartford',
  DD: 'Dundee',
  DE: 'Derby',
  DG: 'Dumfries',
  DH: 'Durham',
  DL: 'Darlington',
  DN: 'Doncaster',
  DT: 'Dorchester',
  DY: 'Dudley',
  E: 'London E1 - 18',
  EL: 'London E1 - 18',
  EC: 'London EC1 - 4',
  EH: 'Edinburgh',
  EN: 'Enfield',
  EX: 'Exeter',
  FK: 'Falkirk',
  FY: 'Blackpool',
  G: 'Glasgow',
  GS: 'Glasgow',
  GL: 'Gloucester',
  GU: 'Guildford',
  GY: 'Guernsey',
  HA: 'Harrow',
  HD: 'Huddersfield',
  HG: 'Harrogate',
  HP: 'Hemel Hempstead',
  HR: 'Hereford',
  HS: 'Outer Hebrides',
  HU: 'Hull',
  HX: 'Halifax',
  IG: 'Ilford',
  IM: 'Isle of Man',
  IP: 'Ipswich',
  IV: 'Inverness',
  JE: 'Jersey',
  KA: 'Kilmarnock',
  KT: 'Kingston upon Thames',
  KW: 'Orkney',
  KY: 'Kirkcaldy',
  L: 'Liverpool',
  LP: 'Liverpool',
  LA: 'Lancaster',
  LD: 'Llandrindod Wells',
  LE: 'Leicester',
  LL: 'Llandudno',
  LN: 'Lincoln',
  LS: 'Leeds',
  LU: 'Luton',
  M: 'Manchester',
  MR: 'Manchester',
  ME: 'Medway',
  MK: 'Milton Keynes',
  ML: 'Motherwell',
  N: 'London N1 - 22',
  NL: 'London N1 - 22',
  NE: 'Newcastle upon Tyne',
  NG: 'Nottingham',
  NN: 'Northampton',
  NP: 'Newport',
  NK: 'Norwich',
  NW: 'London NW1 - 11',
  OL: 'Oldham',
  OX: 'Oxford',
  PA: 'Paisley',
  PE: 'Peterborough',
  PH: 'Perth',
  PL: 'Plymouth',
  PO: 'Portsmouth',
  PR: 'Preston',
  RG: 'Reading',
  RH: 'Redhill',
  RM: 'Romford',
  S: 'Sheffield',
  SD: 'Sheffield',
  SA: 'Swansea',
  SE: 'London SE1 - 28',
  SG: 'Stevenage',
  SK: 'Stockport',
  SL: 'Slough',
  SM: 'Sutton',
  SN: 'Swindon',
  SO: 'Southampton',
  SP: 'Salisbury',
  SR: 'Sunderland',
  SS: 'Southend on Sea',
  ST: 'Stoke on Trent',
  SW: 'London SW1 - 20',
  SY: 'Shrewsbury',
  TA: 'Taunton',
  TD: 'Tweed',
  TF: 'Telford',
  TN: 'Tonbridge',
  TQ: 'Torquay',
  TR: 'Truro',
  TS: 'Teeside',
  TW: 'Twickenham',
  UB: 'Uxbridge',
  W: 'London W1 - 14',
  WL: 'London W1 - 14',
  WA: 'Warrington',
  WC: 'London WC1 - 2',
  WD: 'Watford',
  WF: 'Wakefield',
  WN: 'Wigan',
  WR: 'Worcester',
  WS: 'Walsall',
  WV: 'Wolverhampton',
  YO: 'York',
  ZE: 'Shetland Isles'
}
