# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '15.5' # min_ios_version_supported

prepare_react_native_project!

linkage = 'static' # ENV['USE_FRAMEWORKS']

$RNMapboxMapsVersion = '= 10.19.4'

if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'polo' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pre_install do |installer|
    $RNMapboxMaps.pre_install(installer)
  end

  post_install do |installer|
    $RNMapboxMaps.post_install(installer)

    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
    # __apply_Xcode_12_5_M1_post_install_workaround(installer)


    # See https://github.com/facebook/folly/issues/2297
    # Modify RCT-Folly Portability.h to disable coroutines
    # Dir.glob(installer.sandbox.root + "RCT-Folly/folly/Portability.h") do |file|
    #   begin
    #     # First try to make the file writable
    #     system "chmod +w #{file}"

    #     contents = File.read(file)
    #     modified_contents = contents.gsub(/#define FOLLY_HAS_COROUTINES 1/, '#define FOLLY_HAS_COROUTINES 0')

    #     # Try writing with elevated privileges if needed
    #     if !File.writable?(file)
    #       system "sudo chmod +w #{file}"
    #     end

    #     File.write(file, modified_contents)

    #     # Optionally restore original permissions
    #     system "chmod -w #{file}"
    #   rescue => e
    #     Pod::UI.warn "Failed to modify Portability.h: #{e.message}"
    #   end
    # end
  end
end
